# Generated by Django 4.2.7 on 2023-11-26 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('entrenador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GeneroJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rango', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('juego_preferido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jugadores.juego')),
                ('plataforma_preferida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jugadores.plataforma')),
            ],
        ),
    ]
