# Generated by Django 4.2.7 on 2023-11-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0002_modo_delete_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='generos_preferidos',
            field=models.ManyToManyField(to='jugadores.generojuego'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='modos_preferidos',
            field=models.ManyToManyField(to='jugadores.modo'),
        ),
    ]
