# Generated by Django 4.2.7 on 2023-11-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0005_rename_fecha_nacimiento_jugador_fecha_de_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='rango',
        ),
        migrations.AddField(
            model_name='jugador',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
    ]
